sudo: required
dist: trusty
compiler: gcc
language: cpp

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
 - sudo add-apt-repository -y ppa:chris-lea/libsodium
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
 - sudo apt-get update
 - sudo apt-get install -y automake libtool gcc-4.8
 - sudo apt-get install -y qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev qt5-default qttools5-dev-tools
 - sudo apt-get install -y libsodium-dev npm
 - sudo npm install -g node-gyp && alias gyp="node-gyp"
 - wget https://codeload.github.com/libuv/libuv/zip/v1.16.1
 - unzip v1.16.1
 - cd libuv-1.16.1
 - sh autogen.sh && ./configure
 - make && make check && sudo make install
 - cd ..

script:
  - cd source_code
  - qmake -project
  - qmake HiveFrame2.pro
  - make
